export const magicalObjects = [
  {knowledge: 80, name: 'capteur de dissimulation', description: 'se met à vibrer dès que quelqu\'un dit un mensonge', cost:1000, side:'+'},
  {knowledge: 60, name: 'clé rétrécissante', description: 'clé qui rétrécit à chaque fois qu\'on la cherche.', cost:20, side:'+'},
  {knowledge: 30, name: 'éteignoir', description: 'éteind les lumières en les capturants', cost:600, side:'+'},
  {knowledge: 90, name: 'frisbee à dent de serpent', description: '-', cost:40, side:'+'},
  {knowledge: 100, name: 'poudre de cheminette', description: 'permet de se télétransporter dans une autre cheminée', cost:5, side:'+'},
  {knowledge: 100, name: 'rapeltout', description: 'boule de verre de la taille d\'une grosse bille qui semble être remplie de fumée, et qui sert à se souvenir de ce qu\'on a oublié de faire.', cost:35, side:'+'},
  {knowledge: 40, name: 'retourneur de temps', description: 'sablier qui permet de remonter le temps. Un retournement de ce sablier correspond à un retour en arrière d\'une heure, deux retournements correspondent à deux heures, etc....', cost:2000, side:'+'},
  {knowledge: 50, name: 'scrutoscope de poche', description: 'lorsque quelqu\'un en qui on ne peut pas avoir confiance se trouve dans les parages, le scrutoscope de poche (sorte de toupie) doit normalement s\'allumer et se mettre à tourner.', cost:200, side:'+'},
  {knowledge: 20, name: 'ceinturon d\'Hermaphrodite', description: 'change le sexe du porteur', cost:75, side:'+'},
  {knowledge: 60, name: 'gantelets de compétences', description: 'augmente 1 compétence de 1d20%', cost:70, side:'+'},
  {knowledge: 40, name: 'gantelets de maladresse', description: 'diminue la dextérité (et compétences liées) de 1d20%', cost:40, side:'-'},
  {knowledge: 60, name: 'bottes de furtivité', description: 'rend les pas du porteur inaudible pour des oreilles humaines', cost:50, side:'+'},
  {knowledge: 60, name: 'bottes de rapidité', description: 'rend le porteur plus rapide (10%) dans tous ses mouvements (dans le même temps la précision est réduite de 10%)', cost:34, side:'+'},
  {knowledge: 60, name: 'bottes nordiques', description: '1d20%  contre le froid', cost:50, side:'+'},
  {knowledge: 60, name: 'bottes d\'atterrissage', description: '1d20% contre les chocs', cost:60, side:'+'},
  {knowledge: 40, name: 'bottes d\'évitement', description: '1d20% contre les projectiles', cost:80, side:'+'},
  {knowledge: 10, name: 'anneau de folie', description: 'rend le porteur fou', cost:45, side:'-'},
  {knowledge: 70, name: 'amulette d\'amitié sincère', description: 'une fois brisée l\'amulette est donnée à un individu qui porte alors une véritable amitié à celui qui la lui a donné (l\'amitié est réciproque)', cost:210, side:'+'},
  {knowledge: 50, name: 'cape de resistance au feu', description: 'rend le porteur résistant aux flammes 1d20%', cost:300, side:'+'},
  {knowledge: 30, name: 'anneau d\'action libre', description: 'immunisé contre tout type d\'immobilisation', cost:620, side:'+'},
  {knowledge: 40, name: 'anneau d\'invisibilité', description: 'rend invisible pendant 10min (1d6 charges)', cost:320, side:'+'},
  {knowledge: 30, name: 'ceinturon perceur', description: 'rend vulnérable aux coupures (1d10%)', cost:65, side:'-'},
  {knowledge: 30, name: 'ceinturon de franchise', description: 'le porteur ne peut plus mentir', cost:85, side:'-'},
  {knowledge: 50, name: 'bracelets de défense', description: 'réduit les dégats de 50%', cost:125, side:'+'},
  {knowledge: 40, name: 'gantelets des ogres', description: 'augmente la force brute de 1d20%', cost:210, side:'+'},
  {knowledge: 30, name: 'amulette de protection+1', description: 'réduit les dégats de 1pt', cost:100, side:'+'},
  {knowledge: 50, name: 'amulette bouclier', description: 'les sorts rebondissent sur le porteur', cost:730, side:'+'},
  {knowledge: 50, name: 'amulette de Néphrite', description: 'augmente la défense sur les charmes de 1d20%', cost:450, side:'+'},
  {knowledge: 80, name: 'collier de projectiles de feu', description: 'permet de lancer 1d6 boules de feu', cost:320, side:'+'},
  {knowledge: 80, name: 'collier de projectiles de glace', description: 'permet de lancer 1d6 boules de glace', cost:320, side:'+'},
  {knowledge: 70, name: 'amulette de charme anti-loups', description: 'fait fuir les loups et loups-garou', cost:920, side:'+'},
  {knowledge: 80, name: 'collier de projectiles de foudre', description: 'permet de lancer 1d6 éclairs', cost:320, side:'+'},
  {knowledge: 70, name: 'parchemin de convoquation de monstres', description: 'permet d\'invoquer 1 monstre 1d6 charges', cost:2320, side:'+'},
  {knowledge: 30, name: 'colier de sommeil', description: 'le porteur tombe dans un sommeil profond', cost:120, side:'-'},
  {knowledge: 60, name: 'amulette d\'effroi', description: 'rend le porteur effrayant 1d20%', cost:490, side:'+'},
  {knowledge: 30, name: 'colier de paralysie', description: 'le porteur est incapable de bouger', cost:320, side:'-'},
  {knowledge: 50, name: 'cape du métamorphe (écureuil)', description: 'transforme le porteur en animal 1d6 charges', cost:730, side:'+'},
  {knowledge: 50, name: 'cape du métamorphe (pie)', description: 'transforme le porteur en animal 1d6 charges', cost:730, side:'+'},
  {knowledge: 50, name: 'cape du métamorphe (fourmi)', description: 'transforme le porteur en animal 1d6 charges', cost:730, side:'+'},
  {knowledge: 50, name: 'cape du métamorphe (panthère)', description: 'transforme le porteur en animal 1d6 charges', cost:730, side:'+'},
  {knowledge: 50, name: 'cape du métamorphe (otarie)', description: 'transforme le porteur en animal 1d6 charges', cost:730, side:'+'},
  {knowledge: 50, name: 'cape du métamorphe (rhinocéros)', description: 'transforme le porteur en animal 1d6 charges', cost:730, side:'+'},
  {knowledge: 50, name: 'cape du métamorphe (éléphant)', description: 'transforme le porteur en animal 1d6 charges', cost:730, side:'+'},
  {knowledge: 50, name: 'cape du métamorphe (loup)', description: 'transforme le porteur en animal 1d6 charges', cost:730, side:'+'},
  {knowledge: 50, name: 'cape d\'ombre', description: 'entoure le porteur d\'ombre (celui-ci n\'est pas géné au niveau de sa vision)', cost:530, side:'+'},
  {knowledge: 30, name: 'robe du mauvais archimage', description: 'réduit tous les sorts du porteur de 1d20%', cost:290, side:'-'},
  {knowledge: 70, name: 'robe du bon archimage', description: 'augmente tous les sorts du porteur de 1d20%', cost:320, side:'+'},
  {knowledge: 30, name: 'robe d\'agressivité', description: 'augmente l\'agressivité et l\'impulsivité du porteur', cost:120, side:'-'},
  {knowledge: 30, name: 'robe de résignation', description: 'augmente l\'apathie et l\'obésissance du porteur', cost:120, side:'-'},
  {knowledge: 70, name: 'cape de charme', description: 'augmente le charisme du porteur de 1d20%', cost:210, side:'+'},
  {knowledge: 40, name: 'cape de non-détection', description: 'rend le porteur indétectable par des sorts/objets magiques', cost:820, side:'+'},
  {knowledge: 20, name: 'cape de déplacement instable', description: 'téléporte le porteur à n\'importe quel moment à 1d20 mètres de distance', cost:750, side:'-'},
  {knowledge: 50, name: 'capuche d\'infravision', description: 'rend le porteur capable de voir quel que soit la lumière', cost:430, side:'+'},
  {knowledge: 30, name: 'capuche de vision nocturne', description: 'le porteur ne voit que dans l\'obscurité totale', cost:390, side:'-'},
  {knowledge: 60, name: 'pendentif de protection', description: 'crée une bulle de protection infranchissable autour du porteur', cost:740, side:'+'},
  {knowledge: 40, name: 'harpe de tumnus', description: 'permet au musicien d\'endormir la méfiance des personnes qui l\'écoutent', cost:820, side:'+'},
  {knowledge: 50, name: 'anneau de saut', description: 'le porteur est capable de faire des sauts de 4m (attention à l\'aterissage)', cost:190, side:'+'},
  {knowledge: 50, name: 'anneau de feuille morte', description: 'le porteur tombe en douceur quel que soit les conditions', cost:740, side:'+'},
  {knowledge: 60, name: 'amulette de serment', description: 'toute personne faisant une promesse au porteur sera obligé de la respecter', cost:1560, side:'+'},
  {knowledge: 30, name: 'robe démoniaque', description: 'passe toutes les capacités du porteur à 75% au bout d\'1d6 utilisations le porteur se transforme en démon et devient incontrolable (irréversible)', cost:6390, side:'-'},
  {knowledge: 40, name: 'anneau d\'illusions', description: 'crée une illusion (durée 10min) d\'une taille max de 5m3, 1d6 charges', cost:1390, side:'+'},
  {knowledge: 30, name: 'anneau vampirique de puissance', description: 'draine la force de la personne touchée de 1d20% pour la conférer au porteur', cost:6490, side:'+'},
  {knowledge: 40, name: 'bottes ailées', description: 'permet au porteur de s\'envoler (jet de vol sur balai)', cost:890, side:'+'},
  {knowledge: 80, name: 'dé de charlatan', description: 'permet d\'avoir toujours le résultat souhaité par le lanceur', cost:65, side:'+'},
  {knowledge: 60, name: 'boucle d\'oreille des larmes éternelles', description: 'si le porteur les lance, celle-ci produisent de l\'eau qui vient inonder la pièce infiniment', cost:155, side:'+'},
  {knowledge: 70, name: 'pipeau de charme d\'animaux', description: 'permet de charmer un animal qui obéira a des ordres simples (ne mettant pas sa vie en danger)', cost:210, side:'+'},
  {knowledge: 50, name: 'gants de chapardeur', description: 'augment la dextérité du porteur d\'1d20%', cost:90, side:'+'},
  {knowledge: 70, name: 'couteau porte bonheur', description: 'ce couteau augmente les chances de réussite de 1d20% pour toute utilisation', cost:75, side:'+'},
  {knowledge: 50, name: 'oeil artificiel', description: 'permet au porteur de voir à 360° (doit être mis à la place d\'un oeil)', cost:890, side:'+'},
  {knowledge: 30, name: 'anneau rétrécissant', description: 'réduit le porteur d\'1mm toutes les heures, ne peut pas être enlevé. Effet annulé si le porteur porte un anneau agrandissant', cost:1300, side:'-'},
  {knowledge: 30, name: 'anneau agrandissant', description: 'agrandit le porteur d\'1mm toutes les heures, ne peut pas être enlevé. Effet annulé si le porteur porte un anneau agrandissant', cost:1300, side:'-'},
  {knowledge: 20, name: 'valise de tardis', description: 'l\'intérieur est aussi grand qu\'une grande demeure, tout ce qui se trouve à l\'intèrieur ne pése rien', cost:4320, side:'+'},
  {knowledge: 30, name: 'sceptre tentaculaire', description: 'se transforme en tentacule capable d\'attraper toute personne à moins de 2m', cost:2340, side:'+'},
  {knowledge: 30, name: 'sceptre du cobra', description: 'si le porteur le lance se transforme en serpent n\'obéissant qu\'au porteur. Redevient un baton si le porteur le touche. 1d6 charges', cost:3200, side:'+'},
  {knowledge: 30, name: 'sac dévoreur', description: 'ce sac dévore et réduit en poussière tout ce qui est mis dedans', cost:870, side:'-'},
  {knowledge: 50, name: 'amulette miroir', description: 'toutes personne voyant le porteur se verra à la place', cost:1230, side:'+'},
  {knowledge: 50, name: 'marionette sans fils', description: 'la marionette reproduit tous les mouvements du possesseur (peut marcher sans que le possesseur ne se déplace)', cost:3240, side:'-'},
  {knowledge: 50, name: 'amulette d\'insonorisation', description: 'tous les sons autour du porteur son annulés sur une distance de 5m (ne passe pas les murs)', cost:1450, side:'+'},
  {knowledge: 40, name: 'lunette d\'identité', description: 'modifie le visage du porteur', cost:940, side:'+'},
  {knowledge: 40, name: 'flûte terrifiante', description: 'sème la confusion sur tous ceux qui l\'écoutent qui se battent entre eux', cost:2600, side:'+'},
  {knowledge: 70, name: 'figurine animale (lynx)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (hiboux)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (hérisson)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (renard)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (cheval)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (hypogriffe)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (mouche)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (python)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (gorille)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (hamster)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 40, name: 'baton portail', description: 'lorsque le porteur fait un mouvement latéral devant lui avec le baton celui-ci se transforme en porte. Une fois la porte passée le porteur est transporté dans une pièce agréable dans une autre dimension (différente à chaque utilisation) et peut récupérer le baton. Il doit refaire le même mouvement pour revenir dans son monde. 1d6 utilisations.', cost:6490, side:'+'},
  {knowledge: 50, name: 'boucle d\'oreille de vérité', description: 'tinte légérement losrque quelqu\'un ment à côté du porteur', cost:670, side:'+'},
  {knowledge: 80, name: 'bouteille fumingène', description: 'une fois ouverte crée une fummée très dense empéchant toutes personne de voir (fait tousser). Effet 10min', cost:140, side:'+'},
  {knowledge: 70, name: 'barque miniature', description: 'une fois posée dans l\'eau cette barque s\'agrandit aux dimensions désirée, elle se déplace seule et reprend sa forme de base une fois sortie de l\'eau', cost:780, side:'+'},
  {knowledge: 50, name: 'anneau de passe-murail', description: 'permet de passer à travers les murs. 1d6 charges', cost:420, side:'+'},
  {knowledge: 40, name: 'colier d\'amnésie', description: 'rend amnésique la personne qui le porte', cost:780, side:'+'},
  {knowledge: 70, name: 'oreille à ralonge', description: 'permet d\'espioner sur une distance de 10m', cost:35, side:'+'},
  {knowledge: 50, name: 'ultra-aimant', description: 'cet aimant attire à lui tout objet métalique à moind de 10m une fois sortie de sa boite', cost:55, side:'+'},
  {knowledge: 50, name: 'botte d\'eau', description: 'permet au porteur de marcher sur l\'eau comme si c\'était un sol solide', cost:320, side:'+'},
  {knowledge: 60, name: 'briquet éternel', description: 'permet d\'allumer n\'importe quel objet inflamable même dans les pires conditions, ce briquet n\'est jamais à court de combustible', cost:125, side:'+'},
  {knowledge: 40, name: 'valise personnelle', description: 'si la valise est ouverte par quelqu\'un d\'autre que son propriétaire, les objets qui s\'y trouvent sont ceux qui devrait naturellement y être.', cost:230, side:'+'},
]