import { random } from "../../helpers/number";

export const magicalObjects = [
  {knowledge: 80, name: 'capteur de dissimulation', description: 'se met à vibrer dès que quelqu\'un dit un mensonge', cost:1000, side:'+'},
  {knowledge: 60, name: 'clé rétrécissante', description: 'clé qui rétrécit à chaque fois qu\'on la cherche.', cost:20, side:'+'},
  {knowledge: 30, name: 'éteignoir', description: 'éteind les lumières en les capturants', cost:600, side:'+'},
  {knowledge: 90, name: 'frisbee à dent de serpent', description: '-', cost:40, side:'+'},
  {knowledge: 100, name: 'poudre de cheminette', description: 'permet de se télétransporter dans une autre cheminée', cost:5, side:'+'},
  {knowledge: 100, name: 'rapeltout', description: 'boule de verre de la taille d\'une grosse bille qui semble être remplie de fumée, et qui sert à se souvenir de ce qu\'on a oublié de faire.', cost:35, side:'+'},
  {knowledge: 40, name: 'retourneur de temps', description: 'sablier qui permet de remonter le temps. Un retournement de ce sablier correspond à un retour en arrière d\'une heure, deux retournements correspondent à deux heures, etc....', cost:2000, side:'+'},
  {knowledge: 50, name: 'scrutoscope de poche', description: 'lorsque quelqu\'un en qui on ne peut pas avoir confiance se trouve dans les parages, le scrutoscope de poche (sorte de toupie) doit normalement s\'allumer et se mettre à tourner.', cost:200, side:'+'},
  {knowledge: 20, name: 'ceinturon d\'Hermaphrodite', description: 'change le sexe du porteur', cost:75, side:'+'},
  {knowledge: 60, name: 'gantelets de compétences', description: 'augmente 1 compétence de 1d20%', cost:70, side:'+'},
  {knowledge: 40, name: 'gantelets de maladresse', description: 'diminue la dextérité (et compétences liées) de 1d20%', cost:40, side:'-'},
  {knowledge: 60, name: 'bottes de furtivité', description: 'rend les pas du porteur inaudible pour des oreilles humaines', cost:50, side:'+'},
  {knowledge: 60, name: 'bottes de rapidité', description: 'rend le porteur plus rapide (10%) dans tous ses mouvements (dans le même temps la précision est réduite de 10%)', cost:34, side:'+'},
  {knowledge: 60, name: 'bottes nordiques', description: '1d20%  contre le froid', cost:50, side:'+'},
  {knowledge: 60, name: 'bottes d\'atterrissage', description: '1d20% contre les chocs', cost:60, side:'+'},
  {knowledge: 40, name: 'bottes d\'évitement', description: '1d20% contre les projectiles', cost:80, side:'+'},
  {knowledge: 10, name: 'anneau de folie', description: 'rend le porteur fou', cost:45, side:'-'},
  {knowledge: 70, name: 'amulette d\'amitié sincère', description: 'une fois brisée l\'amulette est donnée à un individu qui porte alors une véritable amitié à celui qui la lui a donné (l\'amitié est réciproque)', cost:210, side:'+'},
  {knowledge: 50, name: 'cape de resistance au feu', description: 'rend le porteur résistant aux flammes 1d20%', cost:300, side:'+'},
  {knowledge: 30, name: 'anneau d\'action libre', description: 'immunisé contre tout type d\'immobilisation', cost:620, side:'+'},
  {knowledge: 40, name: 'anneau d\'invisibilité', description: 'rend invisible pendant 10min (1d6 charges)', cost:320, side:'+'},
  {knowledge: 30, name: 'ceinturon perceur', description: 'rend vulnérable aux coupures (1d10%)', cost:65, side:'-'},
  {knowledge: 30, name: 'ceinturon de franchise', description: 'le porteur ne peut plus mentir', cost:85, side:'-'},
  {knowledge: 50, name: 'bracelets de défense', description: 'réduit les dégats de 50%', cost:125, side:'+'},
  {knowledge: 40, name: 'gantelets des ogres', description: 'augmente la force brute de 1d20%', cost:210, side:'+'},
  {knowledge: 30, name: 'amulette de protection+1', description: 'réduit les dégats de 1pt', cost:100, side:'+'},
  {knowledge: 50, name: 'amulette bouclier', description: 'les sorts rebondissent sur le porteur', cost:730, side:'+'},
  {knowledge: 50, name: 'amulette de Néphrite', description: 'augmente la défense sur les charmes de 1d20%', cost:450, side:'+'},
  {knowledge: 80, name: 'collier de projectiles de feu', description: 'permet de lancer 1d6 boules de feu', cost:320, side:'+'},
  {knowledge: 80, name: 'collier de projectiles de glace', description: 'permet de lancer 1d6 boules de glace', cost:320, side:'+'},
  {knowledge: 70, name: 'amulette de charme anti-loups', description: 'fait fuir les loups et loups-garou', cost:920, side:'+'},
  {knowledge: 80, name: 'collier de projectiles de foudre', description: 'permet de lancer 1d6 éclairs', cost:320, side:'+'},
  {knowledge: 70, name: 'parchemin de convoquation de monstres', description: 'permet d\'invoquer 1 monstre 1d6 charges', cost:2320, side:'+'},
  {knowledge: 30, name: 'colier de sommeil', description: 'le porteur tombe dans un sommeil profond', cost:120, side:'-'},
  {knowledge: 60, name: 'amulette d\'effroi', description: 'rend le porteur effrayant 1d20%', cost:490, side:'+'},
  {knowledge: 30, name: 'colier de paralysie', description: 'le porteur est incapable de bouger', cost:320, side:'-'},
  {knowledge: 50, name: 'cape du métamorphe (écureuil)', description: 'transforme le porteur en animal 1d6 charges', cost:730, side:'+'},
  {knowledge: 50, name: 'cape du métamorphe (pie)', description: 'transforme le porteur en animal 1d6 charges', cost:730, side:'+'},
  {knowledge: 50, name: 'cape du métamorphe (fourmi)', description: 'transforme le porteur en animal 1d6 charges', cost:730, side:'+'},
  {knowledge: 50, name: 'cape du métamorphe (panthère)', description: 'transforme le porteur en animal 1d6 charges', cost:730, side:'+'},
  {knowledge: 50, name: 'cape du métamorphe (otarie)', description: 'transforme le porteur en animal 1d6 charges', cost:730, side:'+'},
  {knowledge: 50, name: 'cape du métamorphe (rhinocéros)', description: 'transforme le porteur en animal 1d6 charges', cost:730, side:'+'},
  {knowledge: 50, name: 'cape du métamorphe (éléphant)', description: 'transforme le porteur en animal 1d6 charges', cost:730, side:'+'},
  {knowledge: 50, name: 'cape du métamorphe (loup)', description: 'transforme le porteur en animal 1d6 charges', cost:730, side:'+'},
  {knowledge: 50, name: 'cape d\'ombre', description: 'entoure le porteur d\'ombre (celui-ci n\'est pas géné au niveau de sa vision)', cost:530, side:'+'},
  {knowledge: 30, name: 'robe du mauvais archimage', description: 'réduit tous les sorts du porteur de 1d20%', cost:190, side:'-'},
  {knowledge: 70, name: 'robe du bon archimage', description: 'augmente tous les sorts du porteur de 1d20%', cost:320, side:'+'},
  {knowledge: 30, name: 'robe d\'agressivité', description: 'augmente l\'agressivité et l\'impulsivité du porteur', cost:90, side:'-'},
  {knowledge: 30, name: 'robe de résignation', description: 'augmente l\'apathie et l\'obésissance du porteur', cost:120, side:'-'},
  {knowledge: 70, name: 'cape de charme', description: 'augmente le charisme du porteur de 1d20%', cost:210, side:'+'},
  {knowledge: 40, name: 'cape de non-détection', description: 'rend le porteur indétectable par des sorts/objets magiques', cost:820, side:'+'},
  {knowledge: 20, name: 'cape de déplacement instable', description: 'téléporte le porteur à n\'importe quel moment à 1d20 mètres de distance', cost:750, side:'-'},
  {knowledge: 50, name: 'capuche d\'infravision', description: 'rend le porteur capable de voir quel que soit la lumière', cost:430, side:'+'},
  {knowledge: 30, name: 'capuche de vision nocturne', description: 'le porteur ne voit que dans l\'obscurité totale', cost:190, side:'-'},
  {knowledge: 60, name: 'pendentif de protection', description: 'crée une bulle de protection infranchissable autour du porteur', cost:740, side:'+'},
  {knowledge: 40, name: 'harpe de tumnus', description: 'permet au musicien d\'endormir la méfiance des personnes qui l\'écoutent', cost:820, side:'+'},
  {knowledge: 50, name: 'anneau de saut', description: 'le porteur est capable de faire des sauts de 4m (attention à l\'aterissage)', cost:190, side:'+'},
  {knowledge: 50, name: 'anneau de feuille morte', description: 'le porteur tombe en douceur quel que soit les conditions', cost:740, side:'+'},
  {knowledge: 60, name: 'amulette de serment', description: 'toute personne faisant une promesse au porteur sera obligé de la respecter', cost:1560, side:'+'},
  {knowledge: 30, name: 'robe démoniaque', description: 'passe toutes les capacités du porteur à 75% au bout d\'1d6 utilisations le porteur se transforme en démon et devient incontrolable (irréversible)', cost:6390, side:'-'},
  {knowledge: 40, name: 'anneau d\'illusions', description: 'crée une illusion (durée 10min) d\'une taille max de 5m3, 1d6 charges', cost:1390, side:'+'},
  {knowledge: 30, name: 'anneau vampirique de puissance', description: 'draine la force de la personne touchée de 1d20% pour la conférer au porteur', cost:6490, side:'+'},
  {knowledge: 40, name: 'bottes ailées', description: 'permet au porteur de s\'envoler (jet de vol sur balai)', cost:890, side:'+'},
  {knowledge: 80, name: 'dé de charlatan', description: 'permet d\'avoir toujours le résultat souhaité par le lanceur', cost:65, side:'+'},
  {knowledge: 60, name: 'boucle d\'oreille des larmes éternelles', description: 'si le porteur les lance, celle-ci produisent de l\'eau qui vient inonder la pièce infiniment', cost:155, side:'+'},
  {knowledge: 70, name: 'pipeau de charme d\'animaux', description: 'permet de charmer un animal qui obéira a des ordres simples (ne mettant pas sa vie en danger)', cost:210, side:'+'},
  {knowledge: 50, name: 'gants de chapardeur', description: 'augment la dextérité du porteur d\'1d20%', cost:90, side:'+'},
  {knowledge: 70, name: 'couteau porte bonheur', description: 'ce couteau augmente les chances de réussite de 1d20% pour toute utilisation', cost:75, side:'+'},
  {knowledge: 50, name: 'oeil artificiel', description: 'permet au porteur de voir à 360° (doit être mis à la place d\'un oeil)', cost:890, side:'+'},
  {knowledge: 30, name: 'anneau rétrécissant', description: 'réduit le porteur d\'1mm toutes les heures, ne peut pas être enlevé. Effet annulé si le porteur porte un anneau agrandissant', cost:150, side:'-'},
  {knowledge: 30, name: 'anneau agrandissant', description: 'agrandit le porteur d\'1mm toutes les heures, ne peut pas être enlevé. Effet annulé si le porteur porte un anneau agrandissant', cost:150, side:'-'},
  {knowledge: 20, name: 'valise de tardis', description: 'l\'intérieur est aussi grand qu\'une grande demeure, tout ce qui se trouve à l\'intèrieur ne pése rien', cost:4320, side:'+'},
  {knowledge: 30, name: 'sceptre tentaculaire', description: 'se transforme en tentacule capable d\'attraper toute personne à moins de 2m', cost:2340, side:'+'},
  {knowledge: 30, name: 'sceptre du cobra', description: 'si le porteur le lance se transforme en serpent n\'obéissant qu\'au porteur. Redevient un baton si le porteur le touche. 1d6 charges', cost:3200, side:'+'},
  {knowledge: 30, name: 'sac dévoreur', description: 'ce sac dévore et réduit en poussière tout ce qui est mis dedans', cost:20, side:'-'},
  {knowledge: 50, name: 'amulette miroir', description: 'toutes personne voyant le porteur se verra à la place', cost:1230, side:'+'},
  {knowledge: 50, name: 'marionette sans fils', description: 'la marionette reproduit tous les mouvements du possesseur (peut marcher sans que le possesseur ne se déplace)', cost:3240, side:'+'},
  {knowledge: 50, name: 'amulette d\'insonorisation', description: 'tous les sons autour du porteur son annulés sur une distance de 5m (ne passe pas les murs)', cost:1450, side:'+'},
  {knowledge: 40, name: 'lunette d\'identité', description: 'modifie le visage du porteur', cost:940, side:'+'},
  {knowledge: 40, name: 'flûte terrifiante', description: 'sème la confusion sur tous ceux qui l\'écoutent qui se battent entre eux', cost:2600, side:'+'},
  {knowledge: 70, name: 'figurine animale (lynx)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (hiboux)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (hérisson)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (renard)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (cheval)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (hypogriffe)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (mouche)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (python)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (gorille)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 70, name: 'figurine animale (hamster)', description: 'lorsque le porteur la lance celle-ci se transforme en un animal qui obéira à tous les ordres (télépathiques) du porteur. Durée 10min', cost:4300, side:'+'},
  {knowledge: 40, name: 'baton portail', description: 'lorsque le porteur fait un mouvement latéral devant lui avec le baton celui-ci se transforme en porte. Une fois la porte passée le porteur est transporté dans une pièce agréable dans une autre dimension (différente à chaque utilisation) et peut récupérer le baton. Il doit refaire le même mouvement pour revenir dans son monde. 1d6 utilisations.', cost:6490, side:'+'},
  {knowledge: 50, name: 'boucle d\'oreille de vérité', description: 'tinte légérement losrque quelqu\'un ment à côté du porteur', cost:670, side:'+'},
  {knowledge: 80, name: 'bouteille fumigène', description: 'une fois ouverte crée une fummée très dense empéchant toutes personne de voir (fait tousser). Effet 10min', cost:140, side:'+'},
  {knowledge: 70, name: 'barque miniature', description: 'une fois posée dans l\'eau cette barque s\'agrandit aux dimensions désirée, elle se déplace seule et reprend sa forme de base une fois sortie de l\'eau', cost:780, side:'+'},
  {knowledge: 50, name: 'anneau de passe-murail', description: 'permet de passer à travers les murs. 1d6 charges', cost:420, side:'+'},
  {knowledge: 40, name: 'colier d\'amnésie', description: 'rend amnésique la personne qui le porte', cost:780, side:'+'},
  {knowledge: 70, name: 'oreille à ralonge', description: 'permet d\'espioner sur une distance de 10m', cost:35, side:'+'},
  {knowledge: 50, name: 'ultra-aimant', description: 'cet aimant attire à lui tout objet métalique à moins de 10m une fois sortie de sa boite', cost:55, side:'+'},
  {knowledge: 50, name: 'botte d\'eau', description: 'permet au porteur de marcher sur l\'eau comme si c\'était un sol solide', cost:320, side:'+'},
  {knowledge: 60, name: 'briquet éternel', description: 'permet d\'allumer n\'importe quel objet inflamable même dans les pires conditions, ce briquet n\'est jamais à court de combustible', cost:125, side:'+'},
  {knowledge: 40, name: 'valise personnelle', description: 'si la valise est ouverte par quelqu\'un d\'autre que son propriétaire, les objets qui s\'y trouvent sont ceux qui devrait naturellement y être.', cost:230, side:'+'},
  {knowledge: 60, name: 'lunette d\'invisibilité étrange', description: 'Ces lunettes vous rendent complètement invisible... tant que personne ne regarde directement dans votre direction', cost:50, side:'+'},
  {knowledge: 30, name: 'Gobelet de soif', description: 'Ce gobelet toujours plein donne soif à qui boit de son eau', cost:40, side:'-'},
  {knowledge: 35, name: 'Gant du mime', description: 'Ces gants vous font communiquer exclusivement par les gestes', cost:60, side:'-'},
  {knowledge: 70, name: 'Pantalon parachute', description: 'Ce pantalon possède une ficelle qui ouvre un parachute (au niveau des fesses) si on la tire', cost:40, side:'+'},
  {knowledge: 40, name: 'Plume d\'envol', description: 'Cette plume ne peut pas rester d\'en les mains de celui qui la tient quel que soit ses efforts', cost:20, side:'-'},
  {knowledge: 30, name: 'Bottes de marche', description: 'Ces bottes obligent celui qui les porte à marcher, il ne peut plus rester en place', cost:60, side:'-'},
  {knowledge: 20, name: 'Épée de paix', description: 'Cette épée refuse le combat quel que soit la cible, elle devient molle au contact de ce quelle touchera ou frappera l\'air à côté de ce quelle devait toucher', cost:50, side:'-'},
  {knowledge: 30, name: 'Lunettes d\'aveuglement', description: 'Ces lunettes qui au contact permettent de voir à des kilomètre, réduit très rapidement votre champs de vision à peau de chagrin', cost:60, side:'-'},
  {knowledge: 40, name: 'Cape de monologue', description: 'Le porteur de cette cape ce met à monologuer et révèle la moindre de ses pensées', cost:110, side:'-'},
  {knowledge: 50, name: 'Sac sans fond', description: 'On peut y mettre presque tout ce qu\'on veut à condition que cela passe dans l\'ouverture, par contre pour récupérer ses objets c\'est une autre affaire', cost:320, side:'-'},
  {knowledge: 20, name: 'Oreilles pointues', description: 'Ces oreilles ne peuvent pas être retirées... mais ne modifie en rien votre ouïe', cost:70, side:'-'},
  {knowledge: 60, name: 'Miroir étrange', description: 'Ce miroir ne montre que ce qui se trouve derrière vous, vous ne pouvez vous y voir', cost:80, side:'+'},
  {knowledge: 80, name: 'Bouton d\'attache', description: 'Ce bouton s\'attache au premier objet qu\'il touche sans pouvoir être enlevé', cost:10, side:'-'},
  {knowledge: 40, name: 'Fiole de vide', description: 'Cette fiole tout aspire l\'air se trouvant dans la pièce. Aucun effet en extèrieur', cost:140, side:'-'},
  {knowledge: 30, name: 'Balai touristique', description: 'Ce balai magique, vous fait passer par tous les lieux touristiques à visiter de la ville.', cost:140, side:'-'},
  {knowledge: 60, name: 'Loupe rétrécissante', description: 'Cette loupe n\'agrandit pas mais rétrécit les choses que l\'on souhaite observer', cost:40, side:'-'},
  {knowledge: 50, name: 'Cape des grands pieds', description: 'Cette cape agrandit considérablement vos pieds', cost:80, side:'-'},
  {knowledge: 60, name: 'Pull de charisme', description: 'Ce pull augmente votre charisme de 1D20% mais réduit d\'autant votre perception', cost:30, side:'-'},
  {knowledge: 50, name: 'Craie de cachette', description: 'Déssinez votre silhouéte sur le sol, allongez vous dessus en suivant le dessin et vous disparaitrez dans le sol, vous pourrez toujours entendre', cost:10, side:'+'},
  {knowledge: 60, name: 'Dé de chance', description: 'Avant chaque lancé, tirez le dé (1D6) pour augmenter vos chances de réussite, si vous faites plus de 3 vous gagnez 20% de chances de réussite. Dans le cas contraire vous en perdez 20%', cost:30, side:'+'},
  {knowledge: 60, name: 'Horloge décalée', description: 'Cette horloge n\'indique pas et n\'indiquera jamais l\'heure', cost:90, side:'-'},
  {knowledge: 50, name: 'Gourde vide', description: 'Cette gourde est et restera vide...', cost:65, side:'-'},
  {knowledge: 70, name: 'Bille qui ne roule pas', description: 'Pas besoin d\'essayer ça ne marchera pas...', cost:5, side:'+'},
  {knowledge: 80, name: 'Balai magique', description: 'Un balai volant normal, tout ce qu\'il y a de plus normal', cost:325, side:'+'},
  {knowledge: 80, name: 'Anneau cannibale', description: 'Le porteur a de plus en plus faim de chaire fraiche, l\'anneau ne peut pas être enlevé manuellement', cost:125, side:'-'},
  {knowledge: 80, name: 'Anneau de gaucherie', description: 'Le porteur doit relancer tous ses jets entre 10 et 20', cost:25, side:'-'},
  {knowledge: 80, name: 'Anneau de perte de vie', description: 'Le porteur perd un point de vie à cahque réussite critique', cost:65, side:'-'},
  {knowledge: 80, name: 'Anneau dévoreur de sorts', description: 'Le porteur a 10% de chances de plus de rater ses sorts', cost:85, side:'-'},
  {knowledge: 80, name: 'Anneau de vérité', description: 'Le porteur ne peut pas mentir', cost:50, side:'-'},
  {knowledge: 80, name: 'Balai frappeur', description: 'Lorsque le porteur tente de voler avec, le balai commence par voler dans tous les sens pour faire tomber le porteur puis le frappe jusqu\'à perte de connaissance', cost:50, side:'-'},
  {knowledge: 80, name: 'Bandeau d\'intelligence', description: 'Le porteur est confu et à un malus de 20% pour tous ses jets d\'intelligence', cost:80, side:'-'},
  {knowledge: 80, name: 'Bottes danseuses', description: 'Le porteur se met à danser dès que le niveau sonore devient important', cost:120, side:'-'},
  {knowledge: 80, name: 'Boule de cristal', description: 'Le porteur doit faire un jet de constitution pour ne pas être fasciné par la boule pendant 2h', cost:70, side:'-'},
  {knowledge: 80, name: 'Chapeau de déguisement', description: 'Une fois le chapeau mis il ne peut plus être retiré', cost:60, side:'-'},
  {knowledge: 80, name: 'Miroir d\'emprisonnement recouvert d\'un tissu violet', description: 'Celui qui se regarde dedans s\'y retrouve enfermé', cost:60, side:'-'},
  {knowledge: 80, name: 'Filet', description: 'Permet de capturer des poissons, mais enferme le porteur si utiliser sur terre', cost:30, side:'-'},
  {knowledge: 80, name: 'Timbales de rapidité', description: 'Ralenti toute créature qui en entend le son', cost:90, side:'-'},
].map((a, id) => ({...a, id: `${a.knowledge}${1}${id}`}));

export const normalObjects = [
  {knowledge: 100, name: 'Chaudron', description: '', cost:405, side:'+'},
  {knowledge: 100, name: 'Parchemin', description: '', cost:2, side:'+'},
  {knowledge: 100, name: 'Plume', description: '', cost:5, side:'+'},
  {knowledge: 100, name: 'Robe de sorcier', description: '', cost:40, side:'+'},
  {knowledge: 100, name: 'Chapeau de sorcier', description: '', cost:30, side:'+'},
  {knowledge: 100, name: 'Sac en toile', description: 'Peux contenir 5 petits objets', cost:60, side:'+'},
  {knowledge: 100, name: 'Sac en cuir', description: 'Peux contenir 5 petits objets', cost:130, side:'+'},
  {knowledge: 100, name: 'Sac en cuir', description: 'Peux contenir 5 petits objets', cost:530, side:'+'},
  {knowledge: 100, name: 'Sac à dos', description: 'Peux contenir 10 petits objets', cost:75, side:'+'},
  {knowledge: 100, name: 'Carnet de notes', description: '', cost:10, side:'+'},
  {knowledge: 100, name: 'Chaussures', description: '', cost:80, side:'+'},
  {knowledge: 100, name: 'Hiboux', description: '', cost:260, side:'+'},
  {knowledge: 100, name: 'Rat', description: '', cost:60, side:'+'},
  {knowledge: 100, name: 'Crapaud', description: '', cost:80, side:'+'},
  {knowledge: 100, name: 'Furet', description: '', cost:140, side:'+'},
  {knowledge: 100, name: 'Nourriture pour animaux', description: '', cost:15, side:'+'},
  {knowledge: 100, name: 'Cage', description: '', cost:70, side:'+'},
  {knowledge: 100, name: 'Corde', description: '', cost:40, side:'+'},
  {knowledge: 100, name: 'Ficelle', description: '', cost:10, side:'+'},
  {knowledge: 100, name: 'Vêtements moldus miteux', description: '', cost:40, side:'+'},
  {knowledge: 100, name: 'Vêtements moldus corrects', description: '', cost:140, side:'+'},
  {knowledge: 100, name: 'Vêtements moldus riches', description: '', cost:340, side:'+'},
  {knowledge: 100, name: 'Lunettes', description: '', cost:120, side:'+'},
  {knowledge: 100, name: 'Miroir', description: '', cost:20, side:'+'},
  {knowledge: 100, name: 'Craie', description: '', cost:3, side:'+'},
  {knowledge: 100, name: 'Bougie', description: '', cost:5, side:'+'},
  {knowledge: 100, name: 'Gourde', description: '', cost:35, side:'+'},
  {knowledge: 100, name: 'Écharpe', description: '', cost:25, side:'+'},
  {knowledge: 100, name: 'Colier', description: '', cost:40, side:'+'},
  {knowledge: 100, name: 'Bague', description: '', cost:110, side:'+'},
  {knowledge: 100, name: 'Bouteille d\'encre', description: '', cost:30, side:'+'},
  {knowledge: 100, name: 'Montre à gousset (mauvaise qualité)', description: '', cost:90, side:'+'},
  {knowledge: 100, name: 'Montre à gousset', description: '', cost:250, side:'+'},
  {knowledge: 100, name: 'Montre à gousset en or', description: '', cost:650, side:'+'},
  {knowledge: 100, name: 'Fiole pour potion', description: '', cost:25, side:'+'},
  {knowledge: 100, name: 'Aiguille à coudre', description: '', cost:1, side:'+'},
  {knowledge: 100, name: 'Aimant', description: '', cost:4, side:'+'},
  {knowledge: 100, name: 'Anneaux de cryptage', description: '', cost:65, side:'+'},
  {knowledge: 100, name: 'Appeau', description: '', cost:25, side:'+'},
  {knowledge: 100, name: 'Ardoise', description: '', cost:10, side:'+'},
  {knowledge: 100, name: 'Astrolabe', description: '', cost:80, side:'+'},
  {knowledge: 100, name: 'Bague à potion', description: 'peut contenir une dose de potion pendant une demi-journée', cost:250, side:'+'},
  {knowledge: 100, name: 'Baguette de sourcier', description: '', cost:20, side:'+'},
  {knowledge: 100, name: 'Baignoire pliante', description: 'l\'hygiene c\'est important', cost:80, side:'+'},
  {knowledge: 100, name: 'Billes en plomb', description: '', cost:35, side:'+'},
  {knowledge: 100, name: 'Boite à parchemins', description: '', cost:120, side:'+'},
  {knowledge: 100, name: 'Piège à loup', description: '', cost:75, side:'+'},
  {knowledge: 100, name: 'Bougeoir', description: '', cost:30, side:'+'},
  {knowledge: 100, name: 'Bourse', description: '', cost:50, side:'+'},
  {knowledge: 100, name: 'Pipe en bois', description: '', cost:70, side:'+'},
  {knowledge: 100, name: 'Clochette', description: '', cost:25, side:'+'},
  {knowledge: 100, name: 'Cercueil (standard)', description: '', cost:250, side:'+'},
  {knowledge: 100, name: 'Chaine', description: '', cost:50, side:'+'},
  {knowledge: 100, name: 'Chaine factices', description: 'Faciles à briser, mais l\'illusion de solidité est là', cost:25, side:'+'},
  {knowledge: 100, name: 'Chaise pliante', description: '', cost:45, side:'+'},
  {knowledge: 100, name: 'Chevalière', description: '', cost:155, side:'+'},
  {knowledge: 100, name: 'Cire à cacheter', description: '', cost:15, side:'+'},
  {knowledge: 100, name: 'Coffret en bois', description: 'peut contenir 3 petits objets', cost:40, side:'+'},
  {knowledge: 100, name: 'Coffre en bois (S)', description: 'peut contenir 5 petits objets', cost:60, side:'+'},
  {knowledge: 100, name: 'Coffre en bois (M)', description: 'peut contenir 10 petits objets', cost:120, side:'+'},
  {knowledge: 100, name: 'Coffre en bois (L)', description: 'peut contenir 15 petits objets', cost:200, side:'+'},
  {knowledge: 100, name: 'Coffre à double fond (S)', description: 'peut contenir 5 petits objets', cost:200, side:'+'},
  {knowledge: 100, name: 'Combinaison d\'apiculteur', description: '', cost:80, side:'+'},
  {knowledge: 100, name: 'Couverture', description: '', cost:30, side:'+'},
  {knowledge: 100, name: 'Échasses', description: '', cost:50, side:'+'},
  {knowledge: 100, name: 'Echelle pliante', description: '', cost:30, side:'+'},
  {knowledge: 100, name: 'Echelle de corde', description: '', cost:50, side:'+'},
  {knowledge: 100, name: 'Filet à papillons', description: '', cost:30, side:'+'},
  {knowledge: 100, name: 'Flasque', description: '', cost:60, side:'+'},
  {knowledge: 100, name: 'Grapin', description: '', cost:80, side:'+'},
  {knowledge: 100, name: 'Hamac', description: '', cost:70, side:'+'},
  {knowledge: 100, name: 'Bouteille d\'huile', description: '', cost:5, side:'+'},
  {knowledge: 100, name: 'Jambe de bois', description: '', cost:45, side:'+'},
  {knowledge: 100, name: 'Lanterne à bougie', description: '', cost:65, side:'+'},
  {knowledge: 100, name: 'Lime', description: '', cost:35, side:'+'},
  {knowledge: 100, name: 'Lit de camp', description: '', cost:80, side:'+'},
  {knowledge: 100, name: 'Longue vue', description: '', cost:120, side:'+'},
  {knowledge: 100, name: 'Loupe', description: '', cost:30, side:'+'},
  {knowledge: 100, name: 'Marteau', description: '', cost:20, side:'+'},
  {knowledge: 100, name: 'Masse', description: '', cost:20, side:'+'},
  {knowledge: 100, name: 'Panier', description: '', cost:25, side:'+'},
  {knowledge: 100, name: 'Parfum', description: '', cost:250, side:'+'},
  {knowledge: 100, name: 'Pelle', description: '', cost:50, side:'+'},
  {knowledge: 100, name: 'Pioche', description: '', cost:50, side:'+'},
  {knowledge: 100, name: 'Poudre', description: '', cost:130, side:'+'},
  {knowledge: 100, name: 'Sac de couchage', description: '', cost:110, side:'+'},
  {knowledge: 100, name: 'Scie', description: '', cost:35, side:'+'},
  {knowledge: 100, name: 'Siflet', description: '', cost:15, side:'+'},
  {knowledge: 100, name: 'Tente', description: '', cost:150, side:'+'},
  {knowledge: 100, name: 'Théiaire', description: '', cost:80, side:'+'},
  {knowledge: 100, name: 'Aiguille à tricotter tordue', description: '', cost:2, side:'+'},
  {knowledge: 100, name: 'Perruque gigantesque en poil de boursouf', description: '', cost:45, side:'+'},
  {knowledge: 100, name: 'Hermine empaillée', description: '', cost:30, side:'+'},
  {knowledge: 100, name: 'Une phalange avec une étiquette illisible', description: '', cost:100, side:'+'},
  {knowledge: 100, name: 'Une cythare, infestée de vers à bois', description: '', cost:5, side:'+'},
  {knowledge: 100, name: 'Cockatrice empaillée', description: '', cost:75, side:'+'},
  {knowledge: 100, name: 'Chapeau pointu de 1m de haut, avec des étoiles peintes', description: '', cost:75, side:'+'},
  {knowledge: 100, name: 'Une peau de Croup pleine mites', description: '', cost:35, side:'+'},
  {knowledge: 100, name: 'Un sablier rempli de sable', description: '', cost:15, side:'+'},
  {knowledge: 100, name: 'Trois petits Billywig en bronze', description: '', cost:15, side:'+'},
  {knowledge: 100, name: 'Une ceinture de géant avec une boucle créée à partir d\'une roue de chariot', description: '', cost:5, side:'+'},
  {knowledge: 100, name: 'Une sphère en pierre de 30cm de diamètre', description: '', cost:15, side:'+'},
  {knowledge: 100, name: 'Un sac de petits animaux de la ferme en bois', description: '', cost:25, side:'+'},
  {knowledge: 100, name: 'Une épée longue pliée en forme de noeud', description: '', cost:20, side:'+'},
  {knowledge: 100, name: 'Une jarre remplie de têtes de corbeaux dans du formol', description: '', cost:40, side:'+'},
  {knowledge: 100, name: 'Un crochet à viande de 50cm', description: '', cost:60, side:'+'},
  {knowledge: 100, name: 'Une série de marionnettes à enfiler sur la main', description: '', cost:50, side:'+'},
  {knowledge: 100, name: 'Un pot en verre, contenant des têtes réduites d\'êtres humains', description: '', cost:50, side:'+'},
  {knowledge: 100, name: 'Un faux serpent en cuir', description: '', cost:20, side:'+'},
  {knowledge: 100, name: 'Une fausse barbe rousse, pour un humanoïde de grande taille', description: '', cost:30, side:'+'},
  {knowledge: 100, name: 'Plusieurs chapeaux pointu rouge à empiler', description: '', cost:10, side:'+'},
  {knowledge: 100, name: 'Un masque de rhinocéros', description: '', cost:40, side:'+'},
  {knowledge: 100, name: 'Un sac rempli de fausse neige', description: '', cost:10, side:'+'},
  {knowledge: 100, name: 'Une bouteille cachetée contenant de l\'eau vieille de 100 ans', description: '', cost:60, side:'+'},
  {knowledge: 100, name: 'Une bouteille cachetée contenant un rouleau de parchemin', description: '', cost:70, side:'+'},
  {knowledge: 100, name: 'Une toile d\'arraignée à accrocher', description: '', cost:20, side:'+'},
  {knowledge: 100, name: 'Un collier de dents de Magyar à pointe', description: '', cost:90, side:'+'},
  {knowledge: 100, name: 'Une barrique de cire fondue', description: '', cost:25, side:'+'},
  {knowledge: 100, name: 'Une panoplie d\'outils de voleur recouverte de sang (moldu)', description: '', cost:15, side:'+'},
  {knowledge: 100, name: 'Une boite de rangement très platte blanche avec un demiguise gravé', description: '', cost:25, side:'+'},
  {knowledge: 100, name: '20 cadres de miroir sans aucun miroir dedans', description: '', cost:35, side:'+'},
  {knowledge: 100, name: 'Ustensiles de cuisine rouillés avec des armoiries', description: '', cost:65, side:'+'},
  {knowledge: 100, name: 'Un jeu d\'échec en étain où il manque le roi noir et la reine blanche', description: '', cost:50, side:'+'},
  {knowledge: 100, name: 'Un paresseux empaillé', description: '', cost:60, side:'+'},
  {knowledge: 100, name: 'Une pile de couvertures de grimoires sans rien dedans', description: '', cost:30, side:'+'},
  {knowledge: 100, name: 'Un filet de pêche avec un énorme trou dedans', description: '', cost:5, side:'+'},
  {knowledge: 100, name: 'Une ceinture en queues de chat', description: '', cost:10, side:'+'},
  {knowledge: 100, name: 'Une brebis en bois avec une tête de diablotin', description: '', cost:20, side:'+'},
  {knowledge: 100, name: 'Une flûte sans trous', description: '', cost:10, side:'+'},
  {knowledge: 100, name: 'Un faux aileron de requin', description: '', cost:20, side:'+'},
  {knowledge: 100, name: 'Une botte droite', description: '', cost:30, side:'+'},
  {knowledge: 100, name: 'Un kit de déguisement à moitié dévoré', description: '', cost:5, side:'+'},
].map((a, id) => ({...a, id: `${random(1, 9) * 10}${2}${id}`}));

export const foodAndDrinks = {
  drinks: [
    {name: 'Bière', cost: 7},
    {name: 'Bière au beurre', cost: 5},
    {name: 'Just de fruit', cost: 3},
    {name: 'Eau', cost: 2},
    {name: 'Eau de vie', cost: 25},
  ],
  food: [
    {name: 'Porridge', cost: 12},
    {name: 'Fish and chips', cost: 12},
    {name: 'Sunday roast (Rôti de boeuf pommes de terre)', cost: 12},
    {name: 'Chicken pie (Tourte au poulet)', cost: 10},
    {name: 'Kidney pie (Tourte au Boeuf)', cost: 10},
    {name: 'Haggis (panse de brebis farcie)', cost: 10},
    {name: 'Welsh rarebit', cost: 10},
    {name: 'Chicken tika massala', cost: 10},
    {name: 'Toad in the hole (saucisse dans une pâte)', cost: 8},
    {name: 'Kedgerre (plat indien, riz haddock)', cost: 14},
    {name: 'Jelly', cost: 6},
    {name: 'English breakfast', cost: 6},
  ]
};
