import { Spell } from './domain/Spell';

export const spells: Spell[] = [
  {name: "jet d'eau", category: "eau", incantation: "Aquamenti", description: "Crée un jet d'eau comparable à celui d'un tuyau d'arrosage", level: 0},
  {name: "brouillard", category: "eau", incantation: "nebulus", description: "Crée une nappe de brouillard dense sur un rayon de 5m", level: 0},
  {name: "vague d'eau", category: "eau", incantation: "fluctus", description: "Crée une énorme vague d'eau qui vient déferler dans la direction indiquée par la baguette du sorcier, les personnes ou créatures présentes sur son passage tombent au sol. Distance: 5m, largeur: 3m, hauteur 2m", level: 1},
  {name: "fouet d'eau", category: "eau", incantation: "aqua flagella", description: "Crée un fouet d'eau de 4m de longs.", level: 2},
  {name: "sphère d'eau", category: "eau", incantation: "sphaera", description: "Crée une sphère d'eau de 3m de diamètre qui roule dans la direction indiquée par la baguette du sorcier, celle-ci emprisonne les personnes ou créatures prises dans son passage.", level: 3},
  {name: "Golem de glace", category: "eau", incantation: "pupus", description: "Crée une licorne de glace de 4m de haut. Obéissant aux ordres simple du sorcier qui l'a créée. Durée 10min", level: 4},
  {name: "mur d'eau", category: "eau", incantation: "magnus stagnus", description: "Crée un mur infranchissable de 3m de haut et 5m de large. Durée 5min", level: 2},
  {name: "sphere de protection d'eau", category: "eau", incantation: "aquae defensio", description: "Crée une sphère de protection infranchissable de 3m de rayon. Durée 1h (ou suppression par le sorcier qui l'a générée)", level: 3},
  {name: "Saut magique", category: "air", incantation: "ascensio", description: "Génére un souffle puissant de vent capable de faire sauter un sorcier à 3m de haut", level: 0},
  {name: "souffle de vent", category: "air", incantation: "aura", description: "Crée une bourasque de vent (trop faible pour renverser des personnes ou créatures) mais capable d'éteindre de petits feux. Distance 5m", level: 0},
  {name: "décharge", category: "air", incantation: "fulgor", description: "Crée une boule d'énergie autour du sorcier qui vient se décharger sur la 1ere personne ou créature qu'il touche", level: 1},
  {name: "bourrasque", category: "air", incantation: "flippendo", description: "Crée une bourasque de vent violent qui renverse les créatures ou personnes sur son passage. Distance 5m, largeur 3m", level: 2},
  {name: "tornade", category: "air", incantation: "turbo", description: "Crée une tornade de vents violents autour d'une personne ou créature, si celle-ci bouge elle est aussitôt éjectée dans une direction aléatoire à très haute vitesse. Rayon 2m", level: 3},
  {name: "tempête", category: "air", incantation: "meteorribilis", description: "Crée une tempête de vent et de foudre sur un rayon de 30m pendant 1h, toutes les personnes ou créature se trouvant dans cette zone se prenne des éclairs régulièrement.", level: 4},
  {name: "sphere de protection d'air", category: "air", incantation: "aeris defensio", description: "Crée une sphère de protection infranchissable de 3m de rayon. Durée 20min (ou suppression par le sorcier qui l'a générée)", level: 3},
  {name: "mur d'air", category: "air", incantation: "aeris moenia", description: "Crée un mur infranchissable de 3m de haut et 5m de large. Durée 5min", level: 2},
  {name: "brûlure", category: "feu", incantation: "assum ", description: "petite brulure qui fait lâcher prise", level: 0},
  {name: "embrasement", category: "feu", incantation: "incende", description: "embrase un objet inflammable", level: 0},
  {name: "mains brulantes", category: "feu", incantation: "manus ardentes", description: "Rend les mains du sorcier extrêmement chaudes, toutes personnes ou créatures touchées est aussitôt fortement brulée", level: 1},
  {name: "flèche de feu", category: "feu", incantation: "sagitta", description: "Crée une flèche de feu volant rapidement vers une cible", level: 2},
  {name: "explosion", category: "feu", incantation: "eruptio", description: "Fait exploser un objet (50cm3) ou un petit animal (max taille chien)", level: 3},
  {name: "serpent de feu", category: "feu", incantation: "ignis serpens", description: "Crée un énorme serpent de feu d'une taille de 8m de longs obéissant aux ordres simple du sorcier qui l'a invoqué. Durée 10min", level: 4},
  {name: "mur de feu", category: "feu", incantation: "ignis moenia", description: "Crée un mur infranchissable de 3m de haut et 5m de large. Durée 5min", level: 2},
  {name: "sphere de protection de feu", category: "feu", incantation: "ignis defensio", description: "Crée une sphère de protection infranchissable de 3m de rayon. Durée 20min (ou suppression par le sorcier qui l'a générée)", level: 3},
  {name: "trébuchage", category: "terre", incantation: "mala radix", description: "Fait sortir une racine du sol qui fait instantannément trébucher la personne ou créature ciblée.", level: 0},
  {name: "coussinage", category: "terre", incantation: "pulvinatae clunes", description: "Rend une surface de 1m de rayon molle évitant les dégats de collisions", level: 0},
  {name: "entrave", category: "terre", incantation: "amanta radix", description: "Crée un réseau végétal qui pousse sur toutes les surface sur un diamètre de 5m", level: 1},
  {name: "aspersion acide", category: "terre", incantation: "ii acide", description: "Crée une petite balle de liquide acide qui est propulsée dans la direction indiquée par la baguette du sorcier. Au contact le liquide vient ronger ce qu'elle touche.", level: 2},
  {name: "pic rocheux", category: "terre", incantation: "asta acuta", description: "Fait jaillir un pic rocheux de 2m de long et de 50cm de largee d'une surface (sol, mur ou plafond)", level: 3},
  {name: "bosquet de lianes carnivores", category: "terre", incantation: "flores piranhes", description: "Crée un immense réseau végétal de plantes carnivores qui attaques tout ce qui se trouve à porté. Diamètre 10m, durée 1h", level: 4},
  {name: "mur de terre", category: "terre", incantation: "terrae moenia", description: "Crée un mur infranchissable de 3m de haut et 5m de large. Durée 5min", level: 2},
  {name: "sphere de protection de terre", category: "terre", incantation: "terrae defensio", description: "Crée une sphère de protection infranchissable de 3m de rayon. Durée 20min (ou suppression par le sorcier qui l'a générée)", level: 3},
  {name: "chute lente", category: "lévitation", incantation: "lenire", description: "Ralentit la chute d'un petit objet pour qu'il retombe en douceur. 2kg max", level: 0},
  {name: "attraction", category: "lévitation", incantation: "accio", description: "Attire un objet (dont l'emplacement est connu et dans un rayon de 500m max). Poids max 1kg", level: 0},
  {name: "projection", category: "lévitation", incantation: "exite", description: "Ejecte un objet proche (3m max) à grande vitesse. Poids max 1kg", level: 0},
  {name: "lévitation", category: "lévitation", incantation: "wingardium leviosa", description: "Fait léviter un objet proche (3m max) et permet de le déplacer lentement. Poids max 1kg", level: 0},
  {name: "chute lente (2)", category: "lévitation", incantation: "leniree", description: "Ralentit la chute d'une personne, animal ou objet, pour qu'il retombe en douceur. 75kg max", level: 1},
  {name: "attraction (2)", category: "lévitation", incantation: "accioo", description: "Attire un objet (dont l'emplacement est connu et dans un rayon de 500m max). Poids max 25kg", level: 1},
  {name: "projection (2)", category: "lévitation", incantation: "exitee", description: "Ejecte un objet proche (3m max) à grande vitesse. Poids max 25kg", level: 1},
  {name: "lévitation (2)", category: "lévitation", incantation: "wingardium leviosaa", description: "Fait léviter un objet proche (3m max) et permet de le déplacer lentement. Poids max 25kg", level: 1},
  {name: "chute lente (3)", category: "lévitation", incantation: "lenireee", description: "Ralentit la chute de deux personnes, animaux ou objets, pour qu'il retombe en douceur. 150kg total max", level: 2},
  {name: "attraction (3)", category: "lévitation", incantation: "acciooo", description: "Attire un objet (dont l'emplacement est connu et dans un rayon de 500m max). Poids max 50kg", level: 2},
  {name: "projection (3)", category: "lévitation", incantation: "exiteee", description: "Ejecte un objet proche (3m max) à grande vitesse. Poids max 50kg", level: 2},
  {name: "lévitation (3)", category: "lévitation", incantation: "wingardium leviosaaa", description: "Fait léviter un objet proche (3m max) et permet de le déplacer lentement. Poids max 50kg", level: 2},
  {name: "chute lente (4)", category: "lévitation", incantation: "lenireeee", description: "Ralentit la chute de 5 personnes, animaux ou objets, pour qu'il retombe en douceur. 400kg total max", level: 3},
  {name: "attraction (4)", category: "lévitation", incantation: "accioooo", description: "Attire un objet (dont l'emplacement est connu et dans un rayon de 500m max). Poids max 200kg", level: 3},
  {name: "projection (4)", category: "lévitation", incantation: "exiteeee", description: "Ejecte un objet proche (3m max) à grande vitesse. Poids max 200kg", level: 3},
  {name: "lévitation (4)", category: "lévitation", incantation: "wingardium leviosaaaa", description: "Fait léviter un objet proche (3m max) et permet de le déplacer lentement. Poids max 200kg", level: 3},
  {name: "chute lente (5)", category: "lévitation", incantation: "lenireeeee", description: "Ralentit la chute d'un groupe de 13 personnes animaux ou objet de 1000kg total max, pour qu'ils retombent en douceur", level: 4},
  {name: "attraction (5)", category: "lévitation", incantation: "acciooooo", description: "Attire un objet (dont l'emplacement est connu et dans un rayon de 500m max). Poids max 1000kg", level: 4},
  {name: "projection (5)", category: "lévitation", incantation: "exiteeeee", description: "Ejecte un objet proche (3m max) à grande vitesse. Poids max 1000kg", level: 4},
  {name: "lévitation (5)", category: "lévitation", incantation: "wingardium leviosaaaaa", description: "Fait léviter un objet proche (3m max) et permet de le déplacer lentement. Poids max 1000kg", level: 4},
  {name: "solidification", category: "métamorphose", incantation: "duro", description: "Rend une surface solide, ou permet de modeler de petites particules pour créer de petits objets. 5cm max, durée 10min", level: 1},
  {name: "métamorphose d'objet", category: "métamorphose", incantation: "mutare", description: "Transforme de petits objets en quelque chose de même taille. 20cm max, durée 5min", level: 2},
  {name: "conversion", category: "métamorphose", incantation: "converte", description: "Transforme la matière d'un objet ou d'un élément en un autre. Durée 10min", level: 3},
  {name: "attaque", category: "métamorphose", incantation: "oppugno", description: "Anime un objet pour le faire obéir à un sort simple. Durée 20min", level: 4},
  {name: "désarmement", category: "attaque simple", incantation: "expelliarmus", description: "Ejecte l'objet visé de la main de son propriétaire. Distance 4m max. (peut être contré par un Jet de reflexe réussi)", level: 0},
  {name: "glaive spectral", category: "attaque simple", incantation: "gladius", description: "Crée une arme blanche spectrale qui inflige les mêmes dégats qu'une arme réelle. Durée 10min", level: 1},
  {name: "chauve furie", category: "attaque simple", incantation: "vespertilio", description: "Crée une nuée de chauve souris spectrales qui attaquent la cible. Durée 5min, rayon 2m", level: 2},
  {name: "entaille", category: "attaque simple", incantation: "sectumsempra", description: "Crée une lame invisible qui vient taillader la cible dans toutes les directions.", level: 3},
  {name: "baiser du vampire", category: "attaque simple", incantation: "draculam", description: "Aspire l'énergie vitale de la cible pour la donner au lanceur du sort", level: 4},
  {name: "annulation grand sorts", category: "attaque simple", incantation: "finite incantatum", description: "Annule un sort et supprime ses effets", level: 4},
  {name: "annulation", category: "annulation", incantation: "evanesco", description: "Annule les sorts de niveaux 0", level: 0},
  {name: "déviation", category: "annulation", incantation: "nonmihi", description: "Dévie le sort lancé par une autre personne. Jet en contre-attaque la cible ne peux pas faire de nouvelle action complexe pendant ce tour", level: 1},
  {name: "annulation de métamorphose", category: "annulation", incantation: "reverte", description: "Annule les effets des sorts de métamorphoses (animagus compris)", level: 2},
  {name: "effacement", category: "annulation", incantation: "obliterro", description: "Efface les runes présentes sur une surface", level: 3},
  {name: "boussole", category: "détection magique", incantation: "septentrio", description: "Indique au lanceur du sort la direction des points cardinaux", level: 0},
  {name: "empreinte", category: "détection magique", incantation: "vestigium", description: "Fait apparaitre les empreintes de pas et de doigts sur l'ensemble des surface qui ont été touchées récemment", level: 1},
  {name: "cherche propriétaire", category: "détection magique", incantation: "rex refers", description: "Fait glisser/planer un petit objet jusqu'à son propriétaire. (1kg max)", level: 2},
  {name: "révélation de sort", category: "détection magique", incantation: "priori incantatum", description: "Permet de révéler l'ensemble des sorts qui ont été prononcé par une baguette magique (dans l'ordre inverse)", level: 3},
  {name: "révélation de sort (2)", category: "détection magique", incantation: "specialis revelio", description: "permet de révéler les sorts jetés sur une personne ou un objet, ou les ingrédients composant une potion", level: 4},
  {name: "liage", category: "sort de base", incantation: "colligo", description: "fait jaillir des cordes qui attachent solidement les mains ou les pieds d'un individu", level: undefined},
  {name: "déliage", category: "sort de base", incantation: "solvo", description: "dénoue les liens de corde ou de lianes (inefficace en cas de chaines)", level: undefined},
  {name: "illumination", category: "sort de base", incantation: "cincidela", description: "rend un petit objet lumineux. Idéal pour retrouver un objet perdu", level: undefined},
  {name: "ouverture", category: "sort de base", incantation: "alohomora", description: "ouvre une porte fermée non magiquement ou par collaporta", level: undefined},
  {name: "fermeture", category: "sort de base", incantation: "collaporta", description: "ferme une porte et tire le verrou ou la clanche ", level: undefined},
  {name: "explosion de verre", category: "sort de base", incantation: "finestra", description: "fait exploser le verre en minuscules morceaux.", level: undefined},
  {name: "réparation", category: "sort de base", incantation: "reparo", description: "répare un objet fêlé ou cassé. Ne fonctionne pas en cas de débris trop nombreux.", level: undefined},
  {name: "empaquetage", category: "sort de base", incantation: "failamale", description: "permet de placer dans une valise ou malle tous les petits objets dans un rayon de 2m", level: undefined},
  {name: "ficellage", category: "sort de base", incantation: "ligare", description: "fait jaillir des cordes qui ligotent entièrement un individu", level: undefined},
  {name: "extension", category: "sort de base", incantation: "capacious extremis", description: "permet d'augmenter la taille intérieure d'un objet sans en modifier la taille physique de manière à améliorer sa capacité de stockage.", level: undefined},
  {name: "retour", category: "sort de base", incantation: "offero", description: "redonne à un ou plusieurs objets son état initial (répare et range)", level: undefined},
  {name: "atelle", category: "sort de base", incantation: "ferula", description: "crée une petite attelle en bois autour d'un membre blessé", level: undefined},
  {name: "réduction", category: "sort de base", incantation: "reducto", description: "réduit la taille d'un objet, d'un animal ou d'une personne de manière provisoire", level: undefined},
  {name: "empiffrement", category: "sort de base", incantation: "amplificatum", description: "augmente la taille d'un objet, d'un animal ou d'une personne de manière provisoire", level: undefined},
  {name: "surface miroir", category: "sort de base", incantation: "mirare", description: "fait briller une petite surface solide (objet ou mur)", level: undefined},
  {name: "hydrophobie", category: "sort de base", incantation: "pluma anatis", description: "fait qu'un objet ou un tissu repousse l'eau", level: undefined},
  {name: "huile glissante", category: "sort de base", incantation: "oléolubri", description: "", level: undefined},
  {name: "illigibilité", category: "sort de base", incantation: "Illegibilus", description: "fait disparaitre un texte d'un parchemin", level: undefined},
  {name: "riddikulus", category: "sort de base", incantation: "riddikulus", description: "sort d'attaque contre l'épouvantard", level: undefined},
  {name: "renforcement", category: "sort de base", incantation: "fianto duri", description: "renforce l'effet d'un sort provisoire (augmente la puissance et/ou la durée)", level: undefined},
  {name: "lumière", category: "sort de base", incantation: "lumos", description: "fait jaillir un faisceau lumineux de la baguette", level: undefined},
  {name: "nuit", category: "sort de base", incantation: "nox", description: "éteint le dort lumos ou les lumières des alentours", level: undefined},
  {name: "magie domestique", category: "sort de base", incantation: "recurvite", description: "sortilège commode en toute circonstance : permet au choix de laver, rincer, récurrer", level: undefined},
  {name: "air chaud", category: "sort de base", incantation: "calefacio", description: "génère un souffle chaud qui réchauffe et sèche", level: undefined},
  {name: "refroidissage", category: "sort de base", incantation: "refrigo", description: "génère un souffle froid qui rafraichit le sorcier ou refroidit la soupe avant de la boire ou autre utilité si vous en trouvez...", level: undefined},
  {name: "détonation", category: "sort de base", incantation: "bum", description: "sort qui génère un bruit sec et violent (comme une cassure ou une balle)", level: undefined},
  {name: "éclat lumineux", category: "sort de base", incantation: "lux", description: "permet d'envoyer un signal lumineux de la couleur de votre choix dans le ciel - sort silencieux", level: undefined},
  {name: "obscurité", category: "sort de base", incantation: "obscuro", description: "génère une sphère d'obscurité de 4m de rayon pour une durée de 15 mins", level: undefined},
  {name: "patronus", category: "sort de base", incantation: "spero patronum", description: "vous connaissez", level: undefined},
  {name: "fidelitas", category: "sort de base", incantation: "fidelitas", description: "vous connaissez", level: undefined},
  {name: "sort aléatoire du MJ", category: "sort de base", incantation: "niarkniarkniark", description: "vous ne connaissez pas....mais ça va être chouette. Réussite de 100% assurée", level: undefined},
];
