export type Ingredient = {
  scarcity: "Très rare" | "Insolite" | "Usuel" | "Commun";
  name: string;
};

export type PotionType = "Amélioration" | "Attaque" | "Charme" | "Divers" | "Résistance" | "Soin";

export type Potion = {
  type: PotionType,
  name: string;
  description: string;
  ingredients: string[];
};

export const ingredients: Ingredient[] = [
  {name: "venin d'acromantule",scarcity: "Très rare"},
  {name: "pierre de lune",scarcity: "Très rare"},
  {name: "mandragore",scarcity: "Très rare"},
  {name: "sang de dragon",scarcity: "Très rare"},
  {name: "poudre de corne d'éruptif",scarcity: "Insolite"},
  {name: "crotin de licorne arc en ciel",scarcity: "Insolite"},
  {name: "oeufs de serpencendre",scarcity: "Insolite"},
  {name: "poudre de pieuvre",scarcity: "Usuel"},
  {name: "plumes de jobarbille",scarcity: "Usuel"},
  {name: "chenille",scarcity: "Commun"},
  {name: "armoise",scarcity: "Commun"},
  {name: "vers marins",scarcity: "Commun"},
  {name: "éllébore",scarcity: "Commun"},
  {name: "bave de crapaud",scarcity: "Commun"},
  {name: "bergamotte",scarcity: "Commun"},
];

export const potions: Potion[] = [
  {type:"Amélioration", name: "cuir d'éruptif", description: "cette potion améliore la constitution et toutes les compétences qui y sont associées.", ingredients: ["oeufs de serpencendre", "plumes de jobarbille", "bergamotte"]},
  {type:"Amélioration", name: "force brute", description: "cette potion améliore la force et toutes les compétences qui y sont associées.", ingredients: ["oeufs de serpencendre", "plumes de jobarbille", "vers marins"]},
  {type:"Amélioration", name: "cinq sens", description: "cette potion améliore la perception et toutes les compétences qui y sont associées.", ingredients: ["crotin de licorne arc en ciel", "éllébore", "bave de crapaud"]},
  {type:"Amélioration", name: "doigts agiles", description: "cette potion améliore la dextérité et toutes les compétences qui y sont associées.", ingredients: ["oeufs de serpencendre", "armoise", "éllébore"]},
  {type:"Amélioration", name: "aiguise-méninge", description: "Cette potion aiguise les facultés de concentration du personnage et élimine une partie de sa fatigue - antidote de la confusion", ingredients: ["vers marins", "armoise", "bergamotte"]},
  {type:"Amélioration", name: "felix felicis", description: "Cette potion - très difficile à préparer - améliore la chance pendant une heure", ingredients: ["pierre de lune", "venin d'acromantule", "mandragore"]},
  {type:"Amélioration", name: "sonorum", description: "augmente le volume de la voix", ingredients: ["bergamotte", "bergamotte", "bergamotte"]},
  {type:"Amélioration", name: "invisibilité", description: "cette potion rend parfaitement invisible celui qui la boit", ingredients: ["pierre de lune", "crotin de licorne arc en ciel", "poudre de pieuvre"]},
  {type:"Amélioration", name: "potion du nyctalope", description: "cette potion permet de voir dans l'obscurité naturelle - attention, elle ne permet pas de voir à travers les obscurités magiques", ingredients: ["oeufs de serpencendre", "armoise", "éllébore"]},
  {type:"Amélioration", name: "ratatinage", description: "Cette potion permet de faire rétrécir un objet, un animal ou une personne", ingredients: ["crotin de licorne arc en ciel", "éllébore", "bave de crapaud"]},
  {type:"Amélioration", name: "enflure", description: "Cette potion permet d'agrandir un objet, un animal ou une personne", ingredients: ["bergamotte", "bave de crapaud", "poudre de pieuvre"]},
  {type:"Amélioration", name: "polynectar", description: "Fait prendre temporairement l’apparence d’une autre personne. Durée : 1 heure. Remarques : Doit contenir une partie du corps de la personne dont on veut prendre l’apparence. Cette potion est inadaptée aux métamorphoses animales.", ingredients: ["venin d'acromantule", "mandragore", "pierre de lune"]},
  {type:"Amélioration", name: "flotaison", description: "cette potion permet de marcher sur l'eau", ingredients: ["bave de crapaud", "bergamotte", "vers marins"]},
  {type:"Amélioration", name: "potion Lupin", description: "cette potion empêche son consommateur d'être repéré par un sort ou un objet magique ainsi que par les alarmes moldues.", ingredients: ["bergamotte", "bergamotte", "bave de crapaud"]},
  {type:"Amélioration", name: "Caféine", description: "Empêche le consommateur de dormir durant 24 heures. La fatigue le rattrape cependant d’un coup une fois les effets dissipés. Effets secondaires : agitation extrême et difficulté à rester en place.", ingredients: ["bergamotte", "bave de crapaud", "bave de crapaud"]},
  {type:"Amélioration", name: "potion du Vif Argent", description: "cette potion permet d'effectuer toutes ses actions plus rapidement que les autres personnes", ingredients: ["plumes de jobarbille", "bave de crapaud", "poudre de corne d'éruptif"]},
  {type:"Amélioration", name: "Magneto", description: "permet au consommateur d'attirer à lui tous les objets métalliques.", ingredients: ["bergamotte", "bergamotte", "éllébore"]},
  {type:"Amélioration", name: "haleine de dragon", description: "Dote le consommateur d’une haleine de flammes. Permet d’enflammer ou de blesser une personne, lui occasionnant 1d6+1 dégâts de feu.", ingredients: ["poudre de corne d'éruptif", "bave de crapaud", "bergamotte"]},
  {type:"Amélioration", name: "Maglite", description: "Cette potion change les yeux du consommateur en deux puissantes lampes torches.", ingredients: ["éllébore", "éllébore", "bergamotte"]},
  {type:"Amélioration", name: "potion surprise du MJ crochu", description: "effet aléatoire selon l'humeur du MJ", ingredients: ["éllébore", "bergamotte", "bave de crapaud"]},
  {type:"Amélioration", name: "voix de Brooke", description: "La voix du personnage devient suave (améliore la persuasion)", ingredients: ["poudre de pieuvre", "chenille", "éllébore"]},
  {type:"Amélioration", name: "potion de l'eau réale", description: "Cette potion capillaire permet de rendre les cheveux lisses et soyeux. Attention, les effets peuvent être imprévisibles sur les animaux", ingredients: ["éllébore", "éllébore", "bave de crapaud"]},
  {type:"Amélioration", name: "métamorphosis", description: "Cette potion permet à son consommateur de modifier à volonté quelques éléments de son apparence physique. ", ingredients: ["mandragore", "oeufs de serpencendre", "éllébore"]},
  {type:"Amélioration", name: "potion dicaire", description: "Permet à son consommateur d'adopter la voix d'une personne connue (doit contenir un élément du corps de la personne à imiter)", ingredients: ["mandragore", "armoise", "éllébore"]},
  {type:"Amélioration", name: "vieillissement", description: "Permet de vieillir de quelques mois à quelques années en fonction de la quantité de potion absorbée.", ingredients: ["bave de crapaud", "bave de crapaud", "éllébore"]},
  {type:"Attaque", name: "accouphene", description: "cette potion altère l'audition de son consommateur (des accouphènes à la surdité totale)", ingredients: ["vers marins", "bave de crapaud", "vers marins"]},
  {type:"Attaque", name: "somnifère", description: "Plonge la cible dans un profond sommeil.", ingredients: ["plumes de jobarbille", "poudre de pieuvre", "armoise"]},
  {type:"Attaque", name: "bile de Taupe", description: "altère la vue de son consommateur (de la vue brouillée à la cécité complète)", ingredients: ["plumes de jobarbille", "armoise", "oeufs de serpencendre"]},
  {type:"Attaque", name: "hairbust", description: "cette potion fait pousser les cheveux", ingredients: ["vers marins", "vers marins", "vers marins"]},
  {type:"Attaque", name: "potion Dumorvax", description: "fait couler le nez (handicap perception et discretion)", ingredients: ["vers marins", "vers marins", "bergamotte"]},
  {type:"Attaque", name: "potion d'hilarité", description: "Provoque une forte hilarité chez la personne qui la consomme. Effets secondaires : sauts émotionnels et développement de phobies.", ingredients: ["éllébore", "bergamotte", "bergamotte"]},
  {type:"Attaque", name: "potion geignarde", description: "cette potion entraine des crises de larmes incontrôlées (handicap la vue et la discrétion)", ingredients: ["bave de crapaud", "vers marins", "bergamotte"]},
  {type:"Attaque", name: "potion de mutisme", description: "cette potion empêche de parler : le consommateur bouge les lèvres sans émettre davantage que de légers couinements.", ingredients: ["éllébore", "plumes de jobarbille", "bergamotte"]},
  {type:"Attaque", name: "potion de crache-limace", description: "fait cracher des limaces", ingredients: ["bergamotte", "bergamotte", "vers marins"]},
  {type:"Attaque", name: "concentré de pruneaux", description: "cette potion est un puissant laxatif", ingredients: ["bergamotte", "bergamotte", "bergamotte"]},
  {type:"Attaque", name: "glue", description: "Basée sur le sortilège de glue, cette potion permet de créer une glue qui colle deux objets  ensemble.", ingredients: ["vers marins", "bergamotte", "éllébore"]},
  {type:"Attaque", name: "tete en l'air", description: "cette potion inverse la vision et donne l'impression de marcher au plafond (handicape toutes les actions)", ingredients: ["poudre de pieuvre", "mandragore", "bave de crapaud"]},
  {type:"Attaque", name: "potion d'inversion", description: "cette potion inverse la latéralité du corps. La jambe gauche répond au lieu de la droite etc.", ingredients: ["plumes de jobarbille", "mandragore", "bave de crapaud"]},
  {type:"Attaque", name: "babillage", description: "Celui qui consomme cette potion se met à avoir des propos incompréhensibles.", ingredients: ["chenille", "armoise", "bergamotte"]},
  {type:"Attaque", name: "poison sang de dragon", description: "Fabriqué à partir de venin de dragon, ce poison provoque la perte de points de vie chez la personne à raison de 1 par heure jusqu’à ce qu’elle sombre dans l’inconscience. Dans cet état, elle ne peut être ramenée à elle qu’après avoir contré les effets du poison.", ingredients: ["sang de dragon", "sang de dragon", "sang de dragon"]},
  {type:"Attaque", name: "fiel de Rogue", description: "poison lent et indétectable", ingredients: ["sang de dragon", "crotin de licorne arc en ciel", "chenille"]},
  {type:"Attaque", name: "gifle du Dley", description: "poison violent et instantané", ingredients: ["sang de dragon", "crotin de licorne arc en ciel", "armoise"]},
  {type:"Attaque", name: "sirop de Marge", description: "cette potion fait gonfler son consommateur à l'helium. Peut faire voler comme un ballon.", ingredients: ["vers marins", "éllébore", "armoise"]},
  {type:"Attaque", name: "potion de confusion", description: "altère fortement l'attention de son consommateur : il ne peut pas se concentrer, a des trous de mémoire et agit en \"pilotage automatique\"", ingredients: ["poudre de pieuvre", "plumes de jobarbille", "bave de crapaud"]},
  {type:"Charme", name: "rage", description: "rend son consommateur particulièrement agressif envers tout ce qui l'entoure. ", ingredients: ["poudre de corne d'éruptif", "oeufs de serpencendre", "vers marins"]},
  {type:"Charme", name: "cauchemar d'Elias", description: "génère un sentiment de peur panique. Le consommateur se trouve paralysé de peur au moindre évènement.", ingredients: ["poudre de pieuvre", "poudre de corne d'éruptif", "plumes de jobarbille"]},
  {type:"Charme", name: "mélancolie", description: "provoque un profond abattement de la personne qui la consomme. Dès lors, celle-ci ne désire plus rien faire d’autre que rester couchée.", ingredients: ["oeufs de serpencendre", "poudre de pieuvre", "plumes de jobarbille"]},
  {type:"Charme", name: "amortentia", description: "rend son consommateur immédiatement amoureux de la première personne qu'il rencontre.", ingredients: ["poudre de corne d'éruptif", "chenille", "poudre de pieuvre"]},
  {type:"Charme", name: "papillonage", description: "empêche son consommateur de se concentrer sur une seule tâche.", ingredients: ["armoise", "chenille", "bergamotte"]},
  {type:"Charme", name: "possession", description: "permet de prendre possession de l'animal qui consomme la potion. Le sorcier peut alors le contrôler comme sa propre personne.", ingredients: ["pierre de lune", "crotin de licorne arc en ciel", "éllébore"]},
  {type:"Charme", name: "transfert", description: "permet de transférer son esprit à un animal. L'esprit de l'animal prend alors possession du corps du créateur de la potion.", ingredients: ["crotin de licorne arc en ciel", "poudre de pieuvre", "bave de crapaud"]},
  {type:"Charme", name: "potion potionnante de Jean Michel", description: "cette potion persuade son consommateur que la personne dont un prélèvement se trouve dans la potion est son meilleur ami.", ingredients: ["crotin de licorne arc en ciel", "poudre de pieuvre", "armoise"]},
  {type:"Charme", name: "béatitude", description: "cette potion rend son consommateur anormalement insouciant. Il ne peut alors envisager l'idée que quelque chose puisse mal tourner ou que quelqu'un soit malintentionné.", ingredients: ["crotin de licorne arc en ciel", "poudre de pieuvre", "vers marins"]},
  {type:"Charme", name: "faux souvenir", description: "cette potion permet d'implanter un faux souvenir dans l'esprit de son consommateur", ingredients: ["sang de dragon", "poudre de corne d'éruptif", "éllébore"]},
  {type:"Charme", name: "potion de kamikaze", description: "cette potion altère la perception du danger. Son consommateur est amené à prendre des risques inconsidérés.", ingredients: ["poudre de corne d'éruptif", "poudre de pieuvre", "vers marins"]},
  {type:"Charme", name: "véritaserum", description: "Le Veritaserum est un puissant sérum de vérité qui oblige le consommateur à dire la vérité. Effet secondaire : fait parler d'une voix monocorde. Remarques : le Veritaserum n'est pas infaillible. Il est plus efficace sur des personnes vulnérables, insuffisamment compétentes pour s'en protéger ou inconscientes du fait qu'on va l'utiliser sur elles. Un sorcier peut se sceller la gorge et produire de fausses déclarations, transformer la potion en un breuvage inoffensif ou utiliser l'occlumancie pour en contrer les effets", ingredients: ["pierre de lune", "pierre de lune", "venin d'acromantule"]},
  {type:"Charme", name: "Pandorine", description: "potion qui rend son consommateur irréstiblement attiré par les personnes de sexe opposé des environs.", ingredients: ["oeufs de serpencendre", "bave de crapaud", "éllébore"]},
  {type:"Charme", name: "amnésie", description: "Cette potion provoque une perte de mémoire chez celui qui en boit.", ingredients: ["sang de dragon", "sang de dragon", "pierre de lune"]},
  {type:"Charme", name: "phéromones", description: "cette potion permet à son consommateur d'attirer à lui tous les animaux de l'espèce dont il a déposé un échantillon dans la potion.", ingredients: ["armoise", "éllébore", "bave de crapaud"]},
  {type:"Charme", name: "potion d'Ora l'exploratrice", description: "cette potion accorde à son consommateur une terrible malchance", ingredients: ["poudre de pieuvre", "plumes de jobarbille", "oeufs de serpencendre"]},
  {type:"Charme", name: "potion du Prince", description: "cette potion persuade son consommateur qu'il est une grenouille. Il se comporte donc comme tel.", ingredients: ["poudre de pieuvre", "armoise", "vers marins"]},
  {type:"Charme", name: "Imperium", description: "Cette potion conduit son consommateur à une obéissance absolue envers la personne dont un prélèvement se trouve dedans.", ingredients: ["pierre de lune", "venin d'acromantule", "venin d'acromantule"]},
  {type:"Divers", name: "acide", description: "cette potion est un acide extremement puissant", ingredients: ["poudre de pieuvre", "vers marins", "bergamotte"]},
  {type:"Divers", name: "récurage", description: "puissant détergent permettant de nettoyer toute tache", ingredients: ["bave de crapaud", "bave de crapaud", "vers marins"]},
  {type:"Divers", name: "potion de brume", description: "cette potion se transforme en brume épaisse et se répand dans l'air dès son contact avec l'air", ingredients: ["chenille", "bave de crapaud", "armoise"]},
  {type:"Divers", name: "combinaison", description: "Cette potion n’a pas d’effet particulier si ce n’est qu’elle permet de combiner les effets de différentes potions et sorts dans une seule potion. Effet secondaire : de nouveaux effets aléatoires peuvent apparaître.", ingredients: ["sang de dragon", "sang de dragon", "venin d'acromantule"]},
  {type:"Résistance", name: "potion pikpik", description: "Augmente la résistance aux feux naturels même d'origine magique", ingredients: ["mandragore", "poudre de pieuvre", "chenille"]},
  {type:"Résistance", name: "potion glagla", description: "Augmente la résistance au froid même d'origine magique", ingredients: ["pierre de lune", "poudre de corne d'éruptif", "chenille"]},
  {type:"Résistance", name: "tetembule", description: "Permet au consommateur de respirer sous l'eau.", ingredients: ["poudre de pieuvre", "vers marins", "bave de crapaud"]},
  {type:"Résistance", name: "potion de raclette", description: "Augmente le poids du consommateur de manière à résister aux sorts de lévitation.", ingredients: ["chenille", "chenille", "chenille"]},
  {type:"Résistance", name: "potion de sceptissisme", description: "Augmente la résistance aux sorts et aux potions de charme", ingredients: ["éllébore", "armoise", "poudre de pieuvre"]},
  {type:"Résistance", name: "potion de faraday", description: "Augmente la résistance aux attaques mentales (imperium, legilimancie...)", ingredients: ["poudre de pieuvre", "oeufs de serpencendre", "chenille"]},
  {type:"Résistance", name: "la chopine", description: "résistance aux sorts niveau 1", ingredients: ["chenille", "chenille", "armoise"]},
  {type:"Résistance", name: "la magnum", description: "résistance aux sorts niveau 2", ingredients: ["poudre de pieuvre", "plumes de jobarbille", "oeufs de serpencendre"]},
  {type:"Résistance", name: "la jéroboam", description: "résistance aux sorts niveau 3", ingredients: ["poudre de pieuvre", "poudre de corne d'éruptif", "sang de dragon"]},
  {type:"Résistance", name: "la nabuchodonosor", description: "résistance aux sorts de niveau 4", ingredients: ["sang de dragon", "mandragore", "oeufs de serpencendre"]},
  {type:"Soin", name: "essence de dictame", description: "soigne les plaies et blessures ouvertes", ingredients: ["éllébore", "chenille", "bave de crapaud"]},
  {type:"Soin", name: "essence de Murlap", description: "soigne les blessures causées par un sorts (brûlures, souffrances, handicaps physiques)", ingredients: ["armoise", "oeufs de serpencendre", "vers marins"]},
  {type:"Soin", name: "potion O²", description: "empeche l'étouffement", ingredients: ["chenille", "armoise", "armoise"]},
  {type:"Soin", name: "potion de sophisme", description: "soigne les blessures infligées à l'âme (troubles anxieux, dépressions, amnésies, confusions diverses)", ingredients: ["oeufs de serpencendre", "armoise", "crotin de licorne arc en ciel"]},
  {type:"Soin", name: "filtre de mandragore", description: "éveille de pétrification", ingredients: ["mandragore", "mandragore", "mandragore"]},
  {type:"Soin", name: "potion de sérénité", description: "permet de calmer le stress, les états anxieux et les conséquences de ceux-ci.", ingredients: ["bergamotte", "bergamotte", "bergamotte"]},
  {type:"Soin", name: "ataraxie", description: "Permet de passer une nuit sans faire de cauchemars, dans un état de béatitude. Effet : Empêche le Sorcier de rêver Effets secondaires : Cette potion rend le sommeil moins réparateur. A très fortes doses et prise sur une longue période, cette potion peut provoquer un coma de quelques jours à quelques semaines", ingredients: ["armoise", "armoise", "armoise"]},
  {type:"Soin", name: "potion de rafistolage", description: "répare les fractures", ingredients: ["oeufs de serpencendre", "chenille", "éllébore"]},
  {type:"Soin", name: "pousse-os", description: "développe la croissance des os, ongles et dents qu'il en manque ou non.", ingredients: ["éllébore", "poudre de corne d'éruptif", "bave de crapaud"]},
  {type:"Soin", name: "antidote niveau 1", description: "Contre les effets des potions basiques ou limite les effets des potions complexes.", ingredients: ["oeufs de serpencendre", "vers marins", "bave de crapaud"]},
  {type:"Soin", name: "Cuvée des Troll", description: "Permet d'annuler ou de modifier les effets d'une potion.", ingredients: ["oeufs de serpencendre", "plumes de jobarbille", "armoise"]},
  {type:"Soin", name: "tue-loup", description: "Cette potion soulage et atténue les symptômes les plus terribles de ceux qui deviennent des loups garous à la pleine lune.", ingredients: ["éllébore", "poudre de pieuvre", "chenille"]},
  {type:"Soin", name: "antidote niveau 2", description: "antidote niveau 2", ingredients: ["poudre de pieuvre", "chenille", "crotin de licorne arc en ciel"]},
];