export const skills = (year: number, prompt: (name: string) => Promise<string>) => ({
  'Acrobatie/Quidditch': {min: 10, max: 60},
  'Artisanat': {min: 5, max: 30 + year * 5},
  'Athlétisme': {min: 20, max: 75},
  'Bagarre': {min: 10, max: 50 + year * 5},
  'Bibliothèque': {min: 15, max: 75 + year * 5},
  'Commandement': {min: 10, max: 60},
  'Connaissance scolaire': {min: 10, max: 50 + year * 5},
  'Déguisement': {min: 5, max: 55},
  'Discrétion': {min: 10, max: 60},
  'Dressage/soin': {min: 10, max: 30 + year * 5},
  'Empathie': {min: 20, max: 75},
  'Esquive': {min: 25, max: 80},
  'Fouille/ménage': {min: 20, max: 80},
  'Langue étrangère': prompt('Langue étrangère').then((name: string) => ({[name]: {min: 0, max: 95}})),
  'Langue natale': {min: 70, max: 95},
  'Orientation': {min: 20, max: 80},
  'Persuasion/Baratin': {min: 10, max: 80},
  'Psychologie': {min: 5, max: 70},
  'Secourisme': {min: 0, max: 20 + year * 5},
  'Survie': {min: 0, max: 20 + year * 5},
  'Triche': {min: 0, max: 40 + year * 5},
  'Vigilance': {min: 20, max: 75},
  'Connaissance': prompt('Connaissance').then((name: string) => ({[name]: ({min: 0, max: 50 + year * 5})})),
  'Connaissance des Moldus': {min: 0, max: 50 + year * 5},
  'Culture générale des sorciers': {min: 20, max: 80},
  'Jeux sorciers': {min: 10, max: 80},
  'Mythes et légendes des sorciers': {min: 5, max: 75},
  'Bricolage': {min: 10, max: 50 + year * 5},
  'Conduite': {min: 0, max: 30 + year * 5},
  'Culture générale Moldue': {min: 20, max: 80},
  'Jeux Moldus': {min: 10, max: 80},
  'Serrurerie': {min: 10, max: 50 + year * 5},
});
